In [1]:
## initially Lets import numpy

import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [7]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
type(arr)

numpy.ndarray

In [10]:
## check the shape of the array

arr.shape

(3, 5)

In [11]:
## Accessing the array elements

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [12]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [13]:
arr[2]

array([9, 7, 6, 8, 9])

In [14]:
arr1

NameError: name 'arr1' is not defined

In [19]:
arr1 = arr.copy()

In [20]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [22]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [23]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])